// Autogenerated by Thrift Compiler (0.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

//
// Group
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Group {
  pub id: i64,
  pub name: String,
  pub description: Option<String>,
  pub created_time: i64,
  pub creator_id: i64,
  pub privacy: String,
  pub member_count: i32,
  pub cover_photo_url: Option<String>,
}

impl Group {
  pub fn new<F3, F8>(id: i64, name: String, description: F3, created_time: i64, creator_id: i64, privacy: String, member_count: i32, cover_photo_url: F8) -> Group where F3: Into<Option<String>>, F8: Into<Option<String>> {
    Group {
      id,
      name,
      description: description.into(),
      created_time,
      creator_id,
      privacy,
      member_count,
      cover_photo_url: cover_photo_url.into(),
    }
  }
}

impl TSerializable for Group {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Group> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<String> = None;
    let mut f_3: Option<String> = None;
    let mut f_4: Option<i64> = None;
    let mut f_5: Option<i64> = None;
    let mut f_6: Option<String> = None;
    let mut f_7: Option<i32> = None;
    let mut f_8: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_string()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i64()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_string()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_i32()?;
          f_7 = Some(val);
        },
        8 => {
          let val = i_prot.read_string()?;
          f_8 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("Group.id", &f_1)?;
    verify_required_field_exists("Group.name", &f_2)?;
    verify_required_field_exists("Group.created_time", &f_4)?;
    verify_required_field_exists("Group.creator_id", &f_5)?;
    verify_required_field_exists("Group.privacy", &f_6)?;
    verify_required_field_exists("Group.member_count", &f_7)?;
    let ret = Group {
      id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      name: f_2.expect("auto-generated code should have checked for presence of required fields"),
      description: f_3,
      created_time: f_4.expect("auto-generated code should have checked for presence of required fields"),
      creator_id: f_5.expect("auto-generated code should have checked for presence of required fields"),
      privacy: f_6.expect("auto-generated code should have checked for presence of required fields"),
      member_count: f_7.expect("auto-generated code should have checked for presence of required fields"),
      cover_photo_url: f_8,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("Group");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("id", TType::I64, 1))?;
    o_prot.write_i64(self.id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("name", TType::String, 2))?;
    o_prot.write_string(&self.name)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.description {
      o_prot.write_field_begin(&TFieldIdentifier::new("description", TType::String, 3))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("created_time", TType::I64, 4))?;
    o_prot.write_i64(self.created_time)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("creator_id", TType::I64, 5))?;
    o_prot.write_i64(self.creator_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("privacy", TType::String, 6))?;
    o_prot.write_string(&self.privacy)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("member_count", TType::I32, 7))?;
    o_prot.write_i32(self.member_count)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.cover_photo_url {
      o_prot.write_field_begin(&TFieldIdentifier::new("cover_photo_url", TType::String, 8))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// Page
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Page {
  pub id: i64,
  pub name: String,
  pub description: Option<String>,
  pub category: String,
  pub created_time: i64,
  pub website: Option<String>,
  pub follower_count: i32,
  pub profile_picture_url: Option<String>,
  pub is_verified: bool,
}

impl Page {
  pub fn new<F3, F6, F8>(id: i64, name: String, description: F3, category: String, created_time: i64, website: F6, follower_count: i32, profile_picture_url: F8, is_verified: bool) -> Page where F3: Into<Option<String>>, F6: Into<Option<String>>, F8: Into<Option<String>> {
    Page {
      id,
      name,
      description: description.into(),
      category,
      created_time,
      website: website.into(),
      follower_count,
      profile_picture_url: profile_picture_url.into(),
      is_verified,
    }
  }
}

impl TSerializable for Page {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Page> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<String> = None;
    let mut f_3: Option<String> = None;
    let mut f_4: Option<String> = None;
    let mut f_5: Option<i64> = None;
    let mut f_6: Option<String> = None;
    let mut f_7: Option<i32> = None;
    let mut f_8: Option<String> = None;
    let mut f_9: Option<bool> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_string()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_string()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_string()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i64()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_string()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_i32()?;
          f_7 = Some(val);
        },
        8 => {
          let val = i_prot.read_string()?;
          f_8 = Some(val);
        },
        9 => {
          let val = i_prot.read_bool()?;
          f_9 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("Page.id", &f_1)?;
    verify_required_field_exists("Page.name", &f_2)?;
    verify_required_field_exists("Page.category", &f_4)?;
    verify_required_field_exists("Page.created_time", &f_5)?;
    verify_required_field_exists("Page.follower_count", &f_7)?;
    verify_required_field_exists("Page.is_verified", &f_9)?;
    let ret = Page {
      id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      name: f_2.expect("auto-generated code should have checked for presence of required fields"),
      description: f_3,
      category: f_4.expect("auto-generated code should have checked for presence of required fields"),
      created_time: f_5.expect("auto-generated code should have checked for presence of required fields"),
      website: f_6,
      follower_count: f_7.expect("auto-generated code should have checked for presence of required fields"),
      profile_picture_url: f_8,
      is_verified: f_9.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("Page");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("id", TType::I64, 1))?;
    o_prot.write_i64(self.id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("name", TType::String, 2))?;
    o_prot.write_string(&self.name)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.description {
      o_prot.write_field_begin(&TFieldIdentifier::new("description", TType::String, 3))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("category", TType::String, 4))?;
    o_prot.write_string(&self.category)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("created_time", TType::I64, 5))?;
    o_prot.write_i64(self.created_time)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.website {
      o_prot.write_field_begin(&TFieldIdentifier::new("website", TType::String, 6))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("follower_count", TType::I32, 7))?;
    o_prot.write_i32(self.follower_count)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.profile_picture_url {
      o_prot.write_field_begin(&TFieldIdentifier::new("profile_picture_url", TType::String, 8))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("is_verified", TType::Bool, 9))?;
    o_prot.write_bool(self.is_verified)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

