// Autogenerated by Thrift Compiler (0.22.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

//
// Post
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Post {
  pub id: i64,
  pub author_id: i64,
  pub content: String,
  pub media_url: Option<String>,
  pub created_time: i64,
  pub updated_time: Option<i64>,
  pub post_type: String,
  pub visibility: Option<String>,
  pub like_count: i32,
  pub comment_count: i32,
  pub share_count: i32,
}

impl Post {
  pub fn new<F4, F6, F8>(id: i64, author_id: i64, content: String, media_url: F4, created_time: i64, updated_time: F6, post_type: String, visibility: F8, like_count: i32, comment_count: i32, share_count: i32) -> Post where F4: Into<Option<String>>, F6: Into<Option<i64>>, F8: Into<Option<String>> {
    Post {
      id,
      author_id,
      content,
      media_url: media_url.into(),
      created_time,
      updated_time: updated_time.into(),
      post_type,
      visibility: visibility.into(),
      like_count,
      comment_count,
      share_count,
    }
  }
}

impl TSerializable for Post {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Post> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<i64> = None;
    let mut f_3: Option<String> = None;
    let mut f_4: Option<String> = None;
    let mut f_5: Option<i64> = None;
    let mut f_6: Option<i64> = None;
    let mut f_7: Option<String> = None;
    let mut f_8: Option<String> = None;
    let mut f_9: Option<i32> = None;
    let mut f_10: Option<i32> = None;
    let mut f_11: Option<i32> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_string()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_string()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i64()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_i64()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_string()?;
          f_7 = Some(val);
        },
        8 => {
          let val = i_prot.read_string()?;
          f_8 = Some(val);
        },
        9 => {
          let val = i_prot.read_i32()?;
          f_9 = Some(val);
        },
        10 => {
          let val = i_prot.read_i32()?;
          f_10 = Some(val);
        },
        11 => {
          let val = i_prot.read_i32()?;
          f_11 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("Post.id", &f_1)?;
    verify_required_field_exists("Post.author_id", &f_2)?;
    verify_required_field_exists("Post.content", &f_3)?;
    verify_required_field_exists("Post.created_time", &f_5)?;
    verify_required_field_exists("Post.post_type", &f_7)?;
    verify_required_field_exists("Post.like_count", &f_9)?;
    verify_required_field_exists("Post.comment_count", &f_10)?;
    verify_required_field_exists("Post.share_count", &f_11)?;
    let ret = Post {
      id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      author_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
      content: f_3.expect("auto-generated code should have checked for presence of required fields"),
      media_url: f_4,
      created_time: f_5.expect("auto-generated code should have checked for presence of required fields"),
      updated_time: f_6,
      post_type: f_7.expect("auto-generated code should have checked for presence of required fields"),
      visibility: f_8,
      like_count: f_9.expect("auto-generated code should have checked for presence of required fields"),
      comment_count: f_10.expect("auto-generated code should have checked for presence of required fields"),
      share_count: f_11.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("Post");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("id", TType::I64, 1))?;
    o_prot.write_i64(self.id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("author_id", TType::I64, 2))?;
    o_prot.write_i64(self.author_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("content", TType::String, 3))?;
    o_prot.write_string(&self.content)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.media_url {
      o_prot.write_field_begin(&TFieldIdentifier::new("media_url", TType::String, 4))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("created_time", TType::I64, 5))?;
    o_prot.write_i64(self.created_time)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.updated_time {
      o_prot.write_field_begin(&TFieldIdentifier::new("updated_time", TType::I64, 6))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("post_type", TType::String, 7))?;
    o_prot.write_string(&self.post_type)?;
    o_prot.write_field_end()?;
    if let Some(ref fld_var) = self.visibility {
      o_prot.write_field_begin(&TFieldIdentifier::new("visibility", TType::String, 8))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("like_count", TType::I32, 9))?;
    o_prot.write_i32(self.like_count)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("comment_count", TType::I32, 10))?;
    o_prot.write_i32(self.comment_count)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("share_count", TType::I32, 11))?;
    o_prot.write_i32(self.share_count)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// Comment
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Comment {
  pub id: i64,
  pub post_id: i64,
  pub author_id: i64,
  pub content: String,
  pub created_time: i64,
  pub updated_time: Option<i64>,
  pub parent_comment_id: Option<i64>,
  pub like_count: i32,
}

impl Comment {
  pub fn new<F6, F7>(id: i64, post_id: i64, author_id: i64, content: String, created_time: i64, updated_time: F6, parent_comment_id: F7, like_count: i32) -> Comment where F6: Into<Option<i64>>, F7: Into<Option<i64>> {
    Comment {
      id,
      post_id,
      author_id,
      content,
      created_time,
      updated_time: updated_time.into(),
      parent_comment_id: parent_comment_id.into(),
      like_count,
    }
  }
}

impl TSerializable for Comment {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Comment> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<i64> = None;
    let mut f_3: Option<i64> = None;
    let mut f_4: Option<String> = None;
    let mut f_5: Option<i64> = None;
    let mut f_6: Option<i64> = None;
    let mut f_7: Option<i64> = None;
    let mut f_8: Option<i32> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_string()?;
          f_4 = Some(val);
        },
        5 => {
          let val = i_prot.read_i64()?;
          f_5 = Some(val);
        },
        6 => {
          let val = i_prot.read_i64()?;
          f_6 = Some(val);
        },
        7 => {
          let val = i_prot.read_i64()?;
          f_7 = Some(val);
        },
        8 => {
          let val = i_prot.read_i32()?;
          f_8 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("Comment.id", &f_1)?;
    verify_required_field_exists("Comment.post_id", &f_2)?;
    verify_required_field_exists("Comment.author_id", &f_3)?;
    verify_required_field_exists("Comment.content", &f_4)?;
    verify_required_field_exists("Comment.created_time", &f_5)?;
    verify_required_field_exists("Comment.like_count", &f_8)?;
    let ret = Comment {
      id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      post_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
      author_id: f_3.expect("auto-generated code should have checked for presence of required fields"),
      content: f_4.expect("auto-generated code should have checked for presence of required fields"),
      created_time: f_5.expect("auto-generated code should have checked for presence of required fields"),
      updated_time: f_6,
      parent_comment_id: f_7,
      like_count: f_8.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("Comment");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("id", TType::I64, 1))?;
    o_prot.write_i64(self.id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("post_id", TType::I64, 2))?;
    o_prot.write_i64(self.post_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("author_id", TType::I64, 3))?;
    o_prot.write_i64(self.author_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("content", TType::String, 4))?;
    o_prot.write_string(&self.content)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("created_time", TType::I64, 5))?;
    o_prot.write_i64(self.created_time)?;
    o_prot.write_field_end()?;
    if let Some(fld_var) = self.updated_time {
      o_prot.write_field_begin(&TFieldIdentifier::new("updated_time", TType::I64, 6))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.parent_comment_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("parent_comment_id", TType::I64, 7))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_begin(&TFieldIdentifier::new("like_count", TType::I32, 8))?;
    o_prot.write_i32(self.like_count)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

